early-stopping: 5 
after-epochs: 50
overwrite: true
keep-best: true
type: transformer
transformer-dim-ffn: 1024
enc-depth: 6
dec-depth: 6
transformer-dropout: 0.1
learn-rate: 0.0003
lr-warmup: 16000
lr-decay-inv-sqrt: 16000
lr-report: true
optimizer-params:
  - 0.9
  - 0.98
  - 0.000000001
clip-norm: 5
exponential-smoothing: true

mini-batch-words: 4096
maxi-batch: 100
dropout-src: 0.1
dropout-trg: 0.1

